version: "3"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nihan
      MYSQL_DATABASE: gotodo
      MYSQL_USER: root
      MYSQL_PASSWORD: nihan
    volumes:
      - ./db-data:/var/lib/mysql

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

